package com.iuh.WiseOwlEnglish_Backend.enums;

public enum GameType {
    PICTURE_WORD_MATCHING,
    SOUND_WORD_MATCHING,
    PICTURE_SENTENCE_MATCHING,
    PICTURE_WORD_WRITING,
    PICTURE4_WORD4_MATCHING,
    PRONUNCIATION,
    SENTENCE_HIDDEN_WORD,
    WORD_TO_SENTENCE

}
